version: '3.8'
services: 
  sphinx: 
    build:
      context: .
      dockerfile: ./infrastructure/docker/sphinx/Dockerfile
    tty: true
    ports:
      - ${port}:8000
    volumes: 
      - ${root_dir}/src:/var/src
      - ${root_dir}/build:/var/build]